# Generated by Django 4.2.1 on 2023-05-11 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateTime', models.DateTimeField(verbose_name='案發日期')),
                ('Car', models.CharField(max_length=10)),
                ('Detail', models.CharField(max_length=10)),
                ('Location', models.CharField(max_length=100)),
            ],
        ),
    ]
