# Generated by Django 4.2.1 on 2023-05-13 10:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Active', models.CharField(max_length=10)),
                ('IP', models.GenericIPAddressField()),
                ('Content', models.CharField(max_length=100)),
                ('User', models.CharField(max_length=10)),
                ('DateTime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date modified')),
            ],
        ),
    ]
