# Generated by Django 4.2.1 on 2023-05-13 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_record'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='User',
            new_name='Member',
        ),
    ]
